init_config:

instances:
  [
    {
      "verbose": true,               # print useful info when verbose is true
      "uxp_port": "8080",            # metric port
      "uxp_url": "/metrics",         # metric URL path
      "namespace": "upbound-system", # crossplane and provider location
      "metrics_default": "max",      # select from a predefined set of
                                     # metrics to collect: none, min, more,
                                     # max
    }
  ]
